spring:
  # Lecture de la variable SERVER_PORT
  server:
    port: ${SERVER_PORT:8081} # Utilise 8081 si la variable n'est pas définie

  # Configuration de la Base de Données PostgreSQL
  datasource:
    # Utilise l'IP et le Port définis dans .env
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  # Configuration de JPA (Hibernate)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    show-sql: true