apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-postgres
  labels:
    io.kompose.service: users-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: users-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: users-postgres
    spec:
      containers:
        - name: users-postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: usersDB
            - name: POSTGRES_PASSWORD
              value: sasmasmasrh10
            - name: POSTGRES_USER
              value: saad
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: users-pg-data
      restartPolicy: Always
      volumes:
        - name: users-pg-data
          persistentVolumeClaim:
            claimName: users-pg-data