apiVersion: v1
data:
  JWT_SECRET_KEY: c3ByaW5nLWJvb3QtbWljcm9zZXJ2aWNlcy1hdXRoLXRva2VuLWtleS1zZWNyZXQ=
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SERVER_PORT: "8083"
  SPRING_DATASOURCE_PASSWORD: sasmasmasrh10
  SPRING_DATASOURCE_URL: jdbc:postgresql://users-postgres:5432/usersDB
  SPRING_DATASOURCE_USERNAME: saad
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  USERS_POSTGRES_DB: usersDB
  USERS_POSTGRES_PASSWORD: sasmasmasrh10
  USERS_POSTGRES_PORT: "5433"
  USERS_POSTGRES_USER: saad
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: user-service-user-service--env
  name: user-service--env
